version: 2

sources:
  - name: data_weather
    description: "Dados sobre previsão do tempo para os próximos 16 dias"
    schema: weather_dataset
    loader: bigquery
    meta: 
      owner: "Amanda"
    freshness:
      warn_after: {count: 1 , period: day}
      error_after: {count: 2 , period: day}

    tables:
      - name: raw_weather
        description: "Tabela de dados de previsão do tempo"
        columns:
          - name: ingestion_timestamp
            description: "Timestamp de ingestão dos dados"
            data_tests:
              - not_null
          - name: data
            description: "Dados do Jsonb"
            data_tests:
              - not_null
          - name: id
            description: "Id da previsão do tempo"
            data_tests:
              - not_null
              - unique